### PR TITLE
Fix event piling and a few small issues

### PR DESCRIPTION
**Pull request by nohal**
This fixes the terrible failure observed on my Mac system and also results in the cell import being faster there as a side effect.
The problem was the events were piling up until there simply were too many and the dispatcher failed catastrophically.

Also a few minor issues I spotted on the way are fixed

Tested on macOS and Linux, but I'm out of install permits so didn't try it at all on Windows.

### CODE REVIEW

**Comment by bdbcat** [comment]
Just to confirm my understanding:
It is the lack of wxYield() in the logging functions that causes an event pileup?

**Comment by nohal** [comment]
Yes, it seems so to me

**Comment by bdbcat** [comment]
I'm fine with this, no problem.
Just wondering why it popped up on Sonoma?  We may never know.
I'll merge, and update the catalog plugin after CI finishes.

**Comment by nohal** [comment]
I haven't used S63 on this machine before and the NZ set is 338 charts, which is roughly 6 times more than the usual Antarctic set I see, so it is pretty possible the problem actually always was there, just did not materialize with less events piled..

**Comment by nohal** [comment]
Anyway, if you can check also on a Windows machine before release, it would be great, I'm out of install permits so can't do it here...

**Pull request merged**
